project_id = "qlkynjaxufzckjbgvhtd"

[auth.email]
[auth.email.template.confirmation]
subject = "Welcome to Tunic Tales - Verify Your Email"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Tunic Tales - Reset Your Password"
content_path = "./supabase/templates/recovery.html"

[functions.generate-description]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.delete-account]
verify_jwt = false
